//Colours For Blocks
Blockly.Msg.RULEBLOCK_COLOUR = 290;
Blockly.Msg.ECSBLOCK_COLOUR = 350;
Blockly.Msg.LOGICALEXPRESSION_COLOUR = 15;
Blockly.Msg.PROPERTYBLOCK_COLOUR = 320;
Blockly.Msg.CHECKBLOCK_COLOUR = 220;
Blockly.Msg.RELATIONBLOCK_COLOUR = 240;
